name: Deploy to PROD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: npm install

    - name: Deploy to Firebase
      run: |
        firebase deploy --only hosting
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}